### ISSUE TITLE
Configure Drone CI to run DB integration tests

### ISSUE THREAD

**Issue by byliuyang** [byliuyang/short#204]
Currently, there are only unit tests running on the CI. There is no integration tests covering the GraphQL and RESTful. To avoid breaking critical features in the future, we want to add integration tests to automatically verify those feature are not breaking when merging to master branch.

## Success criteria
Integration tests are running for the branches that have pull requests opened for.

**Comment by fallion** [comment]
Are you using private or cloud Drone?

**Comment by byliuyang** [comment]
@fallion It's running on DigitalOcean virtual private server. I can grant you admin for testing purpose.

**Comment by matthewhartstonge** [comment]
Hey @byliuyang, I see you are running the tests via a docker-in-docker container, do you want the backend configured with tests directly run by drone?

For example, something like this:

```yaml
- name: test backend
    image: golang:1.13
    commands:
      - cd ./backend
      - go mod download
      - go mod verify
      - go test -v .\...
    when:
      event:
        - pull_request
```
