### ISSUE TITLE
Configure Kubernetes

### ISSUE THREAD

**Issue by byliuyang** [byliuyang/short#281]
Short is now depending on Key Gen service. It will also be depending on auth service, feature toggle service, etc... Kubernetes is here to help manage all those services.

**Comment by byliuyang** [comment]
Install & config [microk8s](https://github.com/ubuntu/microk8s) on the server

**Comment by byliuyang** [comment]
Currently, we are using [Microk8s](https://microk8s.io/docs/) for single machine cluster to save money. When we get more traffics in the future, we will switch to full size Kubernetes.

**Comment by byliuyang** [comment]
```yaml
# nginx.yaml
kind: Service
apiVersion: v1
metadata:
  name: ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  externalIPs:
    - load-balancer-ip
```

All domain names should be resolved to `load-balancer-ip`
